/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.BookRevenueController;
import controller.CategoryRevenueController;
import controller.CustomerRevenueController;
import controller.EmployeeRevenueController;
import entity.Admin;
import entity.BookRevenue;
import entity.CategoryRevenue;
import entity.CustomerRevenue;
import entity.EmployeeRevenue;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author huynguyen
 */
public class RevenueStatistics extends javax.swing.JFrame {

    /**
     * Creates new form RevenueStatics
     */
    
    private Admin currAdmin;
    private DefaultTableModel model;

    public RevenueStatistics() {
        setToBookRevenueModel();
        initComponents();
        setDataToBookRevenue();
    }
    
    public RevenueStatistics(Admin admin) {
        currAdmin = admin;
        setToBookRevenueModel();
        initComponents();
        setDataToBookRevenue();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        statisticTable = new javax.swing.JTable();
        revenueStatisticTitle = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        backBtn1 = new javax.swing.JButton();
        showBookBtn = new javax.swing.JButton();
        showCategoryBtn = new javax.swing.JButton();
        showCustomerBtn = new javax.swing.JButton();
        showEmployeeBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        statisticTable.setModel(model);
        statisticTable.getTableHeader().setReorderingAllowed(false);
        statisticTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                statisticTableMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(statisticTable);
        statisticTable.getColumnModel().getColumn(0).setPreferredWidth(300);
        statisticTable.getColumnModel().getColumn(1).setPreferredWidth(50);
        statisticTable.getColumnModel().getColumn(2).setPreferredWidth(50);

        jScrollPane3.setViewportView(jScrollPane4);

        revenueStatisticTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        revenueStatisticTitle.setText("Book Revenue");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 313, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );

        backBtn1.setText("Back to menu");
        backBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backBtn1MouseClicked(evt);
            }
        });
        backBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtn1ActionPerformed(evt);
            }
        });

        showBookBtn.setText("Book");
        showBookBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showBookBtnActionPerformed(evt);
            }
        });

        showCategoryBtn.setText("Category");
        showCategoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showCategoryBtnActionPerformed(evt);
            }
        });

        showCustomerBtn.setText("Customer");
        showCustomerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showCustomerBtnActionPerformed(evt);
            }
        });

        showEmployeeBtn.setText("Employee");
        showEmployeeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showEmployeeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(backBtn1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(showBookBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(showCategoryBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(showCustomerBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(showEmployeeBtn)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(backBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(showCategoryBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(showCustomerBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(showBookBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(showEmployeeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 47, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(revenueStatisticTitle)
                .addGap(214, 214, 214))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(revenueStatisticTitle)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backBtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtn1MouseClicked
        // TODO add your handling code here:
        new ControllScreenAdmin().backToMainMenu();
        setVisible(false);
        dispose();
    }//GEN-LAST:event_backBtn1MouseClicked

    private void backBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtn1ActionPerformed
        // TODO add your handling code here:
        new ControllScreenAdmin(currAdmin).backToMainMenu();
        setVisible(false);
        dispose();
    }//GEN-LAST:event_backBtn1ActionPerformed

    private void statisticTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statisticTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_statisticTableMouseClicked

    private void showBookBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showBookBtnActionPerformed
        // TODO add your handling code here:
        revenueStatisticTitle.setText("Book Revenue");
        setToBookRevenueModel();
        setDataToBookRevenue();
        statisticTable.setModel(model);
    }//GEN-LAST:event_showBookBtnActionPerformed

    private void showCategoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showCategoryBtnActionPerformed
        // TODO add your handling code here:
        revenueStatisticTitle.setText("Category Revenue");
        setToCategoryRevenueModel();
        setDataToCategoryRevenue();
        statisticTable.setModel(model);
    }//GEN-LAST:event_showCategoryBtnActionPerformed

    private void showCustomerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showCustomerBtnActionPerformed
        // TODO add your handling code here:
        revenueStatisticTitle.setText("Customer Revenue");
        setToCustomerRevenueModel();
        setDataToCustomerRevenue();
        statisticTable.setModel(model);
    }//GEN-LAST:event_showCustomerBtnActionPerformed

    private void showEmployeeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showEmployeeBtnActionPerformed
        // TODO add your handling code here:
        revenueStatisticTitle.setText("Employee Revenue");
        setToEmployeeRevenueModel();
        setDataToEmployeeRevenue();
        statisticTable.setModel(model);
    }//GEN-LAST:event_showEmployeeBtnActionPerformed

    private void setToBookRevenueModel() {
        String[] columns = {"Book Title", "Quantity", "Total Price"};
        model = new DefaultTableModel(columns, 0);
    }
    
    private void setToCategoryRevenueModel() {
        String[] columns = {"Category", "Quantity", "Total Price"};
        model = new DefaultTableModel(columns, 0);
    }
    
    private void setToCustomerRevenueModel() {
        String[] columns = {"Customer Name", "Phone Number", "Total Price"};
        model = new DefaultTableModel(columns, 0);
    }
    
    private void setToEmployeeRevenueModel() {
        String[] columns = {"Name", "Date of birth", "Account", "Total Price"};
        model = new DefaultTableModel(columns, 0);
    }

    private void setDataToBookRevenue() {
        BookRevenueController con = new BookRevenueController();
        List<BookRevenue> list = con.get();
        model.setRowCount(0);
        Object[] row;
        for (int i = 0; i < list.size(); i++) {
            row = new Object[3];
            row[0] = list.get(i).getTitle();
            row[1] = list.get(i).getQuantity();
            row[2] = list.get(i).getTotalPrice();

            model.addRow(row);
        }
    }
    
    private void setDataToCategoryRevenue() {
        CategoryRevenueController con = new CategoryRevenueController();
        List<CategoryRevenue> list = con.get();
        model.setRowCount(0);
        Object[] row;
        for (int i = 0; i < list.size(); i++) {
            row = new Object[3];
            row[0] = list.get(i).getName();
            row[1] = list.get(i).getQuantity();
            row[2] = list.get(i).getTotalPrice();

            model.addRow(row);
        }
    }
    
    private void setDataToCustomerRevenue() {
        CustomerRevenueController con = new CustomerRevenueController();
        List<CustomerRevenue> list = con.get();
        model.setRowCount(0);
        Object[] row;
        for (int i = 0; i < list.size(); i++) {
            row = new Object[3];
            row[0] = list.get(i).getCustomerName();
            row[1] = list.get(i).getPhoneNumber();
            row[2] = list.get(i).getTotalPrice();

            model.addRow(row);
        }
    }
    
    private void setDataToEmployeeRevenue() {
        EmployeeRevenueController con = new EmployeeRevenueController();
        List<EmployeeRevenue> list = con.get();
        model.setRowCount(0);
        Object[] row;
        for (int i = 0; i < list.size(); i++) {
            row = new Object[4];
            row[0] = list.get(i).getName();
            row[1] = list.get(i).getDob();
            row[2] = list.get(i).getUsername();
            row[3] = list.get(i).getTotalPrice();

            model.addRow(row);
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RevenueStatistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RevenueStatistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RevenueStatistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RevenueStatistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RevenueStatistics().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel revenueStatisticTitle;
    private javax.swing.JButton showBookBtn;
    private javax.swing.JButton showCategoryBtn;
    private javax.swing.JButton showCustomerBtn;
    private javax.swing.JButton showEmployeeBtn;
    private javax.swing.JTable statisticTable;
    // End of variables declaration//GEN-END:variables
}
